/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#2d1506',
        'on-tertiary-fixed-variant': '#5a4309',
        surface: '#f9f4ef',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f9efe8',
        'on-primary': '#ffffff',
        'surface-variant': '#ebe1da',
        'on-background': '#1f1b17',
        secondary: '#6d5b47',
        'primary-fixed-dim': '#eabda3',
        'primary-container': '#6b4a36',
        'secondary-container': '#f7dfc4',
        'tertiary-fixed-dim': '#e4c27d',
        'surface-container-low': '#fcf2eb',
        'secondary-fixed-dim': '#dac3aa',
        primary: '#513421',
        error: '#ba1a1a',
        background: '#f9f4ef',
        'surface-container-high': '#f0e6e0',
        'on-error-container': '#93000a',
        'on-surface': '#1f1b17',
        'on-primary-container': '#e8bba2',
        'surface-container': '#f6ece5',
        tertiary: '#4c3700',
        'primary-fixed': '#ffdbc8',
        'inverse-primary': '#eabda3',
        'surface-tint': '#795742',
        'surface-bright': '#fff8f5',
        'on-secondary-container': '#73614d',
        'tertiary-container': '#664e14',
        'surface-container-highest': '#ebe1da',
        'on-tertiary-fixed': '#261a00',
        'inverse-surface': '#352f2b',
        'on-secondary-fixed-variant': '#544431',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        outline: '#82746d',
        'on-secondary-fixed': '#251909',
        'secondary-fixed': '#f7dfc4',
        'surface-dim': '#e2d8d2',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#e3c17c',
        'on-surface-variant': '#50443e',
        'outline-variant': '#d4c3bb',
        'on-primary-fixed-variant': '#5f402c',
        'tertiary-fixed': '#ffdf9f',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        display: ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
}
